name: Test and deploy the React app
on: push
jobs:
  test-react-app:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code from the repository
        uses: actions/checkout@v3
      - name: Install Node to the machine
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies of the project
        run: npm ci
      - name: Run tests
        run: npm test
  deploy-react-app: #fake deploy just to check the things :)
    needs: test-react-app
    runs-on: ubuntu-latest
    steps:
      - name: Get the code from the repository
        uses: actions/checkout@v3
      - name: Install Node to the machine
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies of the project
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying ... !!!"

